// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6bhlvLHHgfTaEFhxpRvjU8_mp9e-Y98M',
    appId: '1:142028280191:web:5e5e675000e39a52698a4a',
    messagingSenderId: '142028280191',
    projectId: 'chatting-app-942de',
    authDomain: 'chatting-app-942de.firebaseapp.com',
    storageBucket: 'chatting-app-942de.firebasestorage.app',
    measurementId: 'G-QWJYHE99NG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8C3uhi7jLeFubxP7jTHaZh_Z7YF8nv8c',
    appId: '1:142028280191:android:9a677ccfa3391768698a4a',
    messagingSenderId: '142028280191',
    projectId: 'chatting-app-942de',
    storageBucket: 'chatting-app-942de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9gYd4WQh0yhNSawnbW4nL5FD5Ejc4J94',
    appId: '1:142028280191:ios:7ab9efb926821b9b698a4a',
    messagingSenderId: '142028280191',
    projectId: 'chatting-app-942de',
    storageBucket: 'chatting-app-942de.firebasestorage.app',
    iosBundleId: 'com.example.chatnow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9gYd4WQh0yhNSawnbW4nL5FD5Ejc4J94',
    appId: '1:142028280191:ios:7ab9efb926821b9b698a4a',
    messagingSenderId: '142028280191',
    projectId: 'chatting-app-942de',
    storageBucket: 'chatting-app-942de.firebasestorage.app',
    iosBundleId: 'com.example.chatnow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6bhlvLHHgfTaEFhxpRvjU8_mp9e-Y98M',
    appId: '1:142028280191:web:12b3b7b31e3546e1698a4a',
    messagingSenderId: '142028280191',
    projectId: 'chatting-app-942de',
    authDomain: 'chatting-app-942de.firebaseapp.com',
    storageBucket: 'chatting-app-942de.firebasestorage.app',
    measurementId: 'G-4G67BYMX3C',
  );
}
